version: '3.7'

services:

  api:
    container_name: 'guidelineapi'
    image: 'guidelineapi'
    build:
      context: ./GuidelineApi
      dockerfile: ./Dockerfile
    environment:
      DB_CONN: "UserID=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Host=guidelinepostgres;Port=5432;Database=${POSTGRES_DB};"
      SALT: ${SALT}
      JWT_ISSUER: "GuidelineAPI"
      JWT_AUDIENCE: "GuidelineAPI"
      JWT_KEY: ${JWT_KEY} 
    ports:
      - "5278:443"
      - "5279:80"
    depends_on:
      - "postgres"
    networks:
      - guidelineapi-network

  postgres:
    container_name: 'guidelinepostgres'
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB : ${POSTGRES_DB}
    ports:
      - '5432:5432'
    networks:
      - guidelineapi-network
      
  frontend:
    container_name: 'guidelinefrontend'
    image: 'guidelinefrontend'
    build:
      context: ./frontend/th_koeln_barrierefreiheit
      dockerfile: ./Dockerfile
    ports:
      - '8282:8080'
    networks:
      - guidelineapi-network
    
networks:
  guidelineapi-network:
    driver: bridge
